### ISSUE TITLE
Ping fails in a T1040RDB based board

### ISSUE THREAD

**Issue by psarker** [qoriq-open-source/linux#6]
Hi, I am using T1040RDB based board with a NIC card on having BRCM phy, SGMII connection.
Managed to load 4.9 kernel but it appears mgmt port does not get recognised and throws error from fsl_dpaa. 

fsl_mac ffe4e8000.ethernet: FMan MEMAC
fsl_mac ffe4e8000.ethernet: FMan MAC address: 00:12:34:56:78:aa
fsl_mac dpaa-ethernet.0: __devm_request_mem_region(mac) failed
fsl_mac: probe of dpaa-ethernet.0 failed with error -16
fsl_mac dpaa-ethernet.0: __devm_request_mem_region(mac) failed
fsl_mac: probe of dpaa-ethernet.0 failed with error -16
ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver

Any clue/hint/help will be much appreciated.

**Comment by rududoo** [comment]
Hi,

Could you try to revert this patch:
Author: Florian Fainelli <f.fainelli@gmail.com>
Date:   Tue Aug 22 15:24:47 2017 -0700

    fsl/man: Inherit parent device and of_node

    Junote Cai reported that he was not able to get a DSA setup involving the
    Freescale DPAA/FMAN driver to work and narrowed it down to
    of_find_net_device_by_node(). This function requires the network device's
    device reference to be correctly set which is the case here, though we have
    lost any device_node association there.

    The problem is that dpaa_eth_add_device() allocates a "dpaa-ethernet" platform
    device, and later on dpaa_eth_probe() is called but SET_NETDEV_DEV() won't be
    propagating &pdev->dev.of_node properly. Fix this by inherenting both the parent
    device and the of_node when dpaa_eth_add_device() creates the platform device.

    Fixes: 3933961682a3 ("fsl/fman: Add FMan MAC driver")
    Signed-off-by: Florian Fainelli <f.fainelli@gmail.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

**Comment by psarker** [comment]
Hi Rududu,

Thank you for shedding lights on this. As I could not crack it so, I tried 4.14.16 (from this repo) on my board and it is looking much better e.g. ethernet device is created and recognised but still ping is getting failed. Below is the boot up msgs for your reference.
xxx xxx xxx -->
Creating 9 MTD partitions on "fef000000.nor":
0x000000000000-0x000000020000 : "rcw"
0x000000020000-0x000000040000 : "fman-fw"
0x000000040000-0x000000060000 : "u-boot-env"
0x000000060000-0x000000080000 : "siskeys"
0x000000080000-0x0000000a0000 : "device-tree"
0x0000000a0000-0x0000005a0000 : "linux-kernel"
0x0000005a0000-0x000000aa0000 : "root filesystem"
0x000000aa0000-0x000000f40000 : "onie"
0x000000f40000-0x000001000000 : "u-boot"
libphy: Fixed MDIO Bus: probed
ucc_geth_driver: QE UCC Gigabit Ethernet Controller
libphy: Freescale XGMAC MDIO Bus: probed
fsl-fman_xmdio ffe4fc000.mdio: cannot register MDIO bus
libphy: Freescale XGMAC MDIO Bus: probed
mdio_bus ffe4e1000: Error while reading PHY0 reg at 3.3
libphy: Freescale XGMAC MDIO Bus: probed
mdio_bus ffe4e3000: Error while reading PHY0 reg at 3.3
libphy: Freescale XGMAC MDIO Bus: probed
mdio_bus ffe4e5000: Error while reading PHY0 reg at 3.3
libphy: Freescale XGMAC MDIO Bus: probed
libphy: Freescale XGMAC MDIO Bus: probed
mdio_bus ffe4e9000: Error while reading PHY0 reg at 3.3
fsl_dpaa_mac ffe4e0000.ethernet: FMan MEMAC
fsl_dpaa_mac ffe4e0000.ethernet: FMan MAC address: a4:8c:db:95:89:00
fsl_dpa dpaa-ethernet.0 eth0: Probed interface eth0
ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
ehci-pci: EHCI PCI platform driver
ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
ohci-pci: OHCI PCI platform driver
xxx  xxxx xxxx <----

A big thanks to you. Found the patch and going to try this. 
Pinaki

**Comment by psarker** [comment]
My bad luck. 4.14.16 seems reverted that fix and code looks as below:

static struct platform_device *dpaa_eth_add_device(int fman_id,
						   struct mac_device *mac_dev,
						   struct device_node *node)
{
... ..... ..... ..... .... ...
	pdev = platform_device_alloc("dpaa-ethernet", dpaa_eth_dev_cnt);
	if (!pdev) {
		ret = -ENOMEM;
		goto no_mem;
	}

	set_dma_ops(&pdev->dev, get_dma_ops(priv->dev));

	ret = platform_device_add_data(pdev, &data, sizeof(data));
	if (ret)
		goto err;

	ret = platform_device_add(pdev);
	if (ret)
		goto err;

	dpaa_eth_dev_cnt++;
	mutex_unlock(&eth_lock);

	return pdev;
... .. ... ...... ...
}

**Comment by rududoo** [comment]
Hi,

You said you are using a NIC with BRDCM phy connected through SGMII. Are you using a riser card?
Can you describe the configuration?

**Comment by psarker** [comment]
Hi, 
Apology for late reply.
I have been playing with 4.14 kernel and as the part of trial and error, I just removed all other interface definitions from dts file except below:

```
enet4: ethernet@e8000 {
                                phy-handle = <&phy0>;
                                phy-connection-type = "sgmii";
                                local-mac-address = [ A4 8C DB 95 89 00 ];
                                sleep = <&rcpm 0x08000000>;
                        };
                        mdio0: mdio@fc000 {
                                phy0: ethernet-phy@1 {
                                reg = <0x01>;
                                };
```

and it worked well. :) 
Thank you for your assistance. 
I will close this issue.
